//! The panel config baked in at build time, if one was.
//!
//! Generated by `build.rs` from `BARSIGN_DEFAULT_CONFIG` (see `./build.sh
//! --default-config`). The content is the SAME format the panel fetches over
//! TFTP, parsed at boot by the same `LayoutConfig::parse()` -- one format, one
//! parser, and a config can move between the fleet server and the firmware
//! without being rewritten.
//!
//! `None` when nothing was baked in, which is the default: a firmware with no
//! baked config behaves exactly as it always has, falling back to a single
//! panel at the bitstream's own geometry.

include!(concat!(env!("OUT_DIR"), "/default_config.rs"));
