// GENERATED by tools/panelc.py -- do not edit.
//
// Compiled from panels/*.yaml. Widgets become ordered early-returns;
// a lambda is spliced in verbatim at its position in that order.
#![allow(unused_imports, unused_parens, unused_variables, clippy::all)]
use crate::assets::*;
use crate::prim::*;
use crate::program::*;

/// Generated from panels/hello.yaml -- edit the YAML, not this.
///
/// ONE function per row, in two halves: a prologue of everything that
/// depends on y but not x, then the pixel loop. That split is the whole
/// reason a program is affordable, and it is why the prologue is inlined
/// here rather than living in a helper -- a `lambda` widget's own `row:`
/// block is spliced into it, and its locals have to be visible to the
/// loop body below.
///
/// The band test, the `when:` guard, the value lookup and the centring
/// width() all depend only on the row, but were once evaluated inside the
/// pixel loop, per widget, for all 16384 pixels. `ctx.val()` is a linear
/// scan of the value table, and a four-page program asks `page == 'N'` in
/// every widget, so a pixel paid for ~24 of them. Measured on
/// dashboard-home: 20268 cycles per pixel, against 11 for a bare store.
pub fn render_hello(ctx: &Ctx, y: usize, x0: usize, row: &mut [u32]) {
    let _ = (&ctx, y, x0);
    #[allow(non_snake_case)] let FONT_BIG = &FONT_DEJAVUSANS_30;
    #[allow(non_upper_case_globals)] const FONT_BIG_LH: usize = FONT_DEJAVUSANS_30_LH;
    #[allow(non_snake_case)] let FONT_SMALL = &FONT_DEJAVUSANS_13;
    #[allow(non_upper_case_globals)] const FONT_SMALL_LH: usize = FONT_DEJAVUSANS_13_LH;
    // text 'HELLO'
    let g_0 = y >= 8 && y < 8 + FONT_SMALL_LH;
    let (s_0, o_0, e_0) = if g_0 {
        let s = "HELLO";
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'hhmm'
    let g_1 = y >= 30 && y < 30 + FONT_BIG_LH;
    let (s_1, o_1, e_1) = if g_1 {
        let s = ctx.val("hhmm");
        let tw = FONT_BIG.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    let mut b_2 = [0u8; 48];
    // value 'temp'
    let g_2 = y >= 78 && y < 78 + FONT_SMALL_LH;
    let (s_2, o_2, e_2) = if g_2 {
        let s = join3(&mut b_2, "OUTSIDE ", ctx.val("temp"), "°");
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // ---- lambda row: prologue (verbatim) ----
    let edge = y < 2 || y >= ctx.h - 2;
    for (i, p) in row.iter_mut().enumerate() {
        let x = x0 + i;
        *p = (|| -> u32 {
            if g_0 && x >= o_0 && x < e_0 {
                if let Some(c) = FONT_SMALL.cover_at(s_0, x, y, o_0, 8) { return (RAMP_SLATE + c) as u32; }
            }
            if g_1 && x >= o_1 && x < e_1 {
                if let Some(c) = FONT_BIG.cover_at(s_1, x, y, o_1, 30) { return (RAMP_WHITE + c) as u32; }
            }
            if g_2 && x >= o_2 && x < e_2 {
                if let Some(c) = FONT_SMALL.cover_at(s_2, x, y, o_2, 78) { return (RAMP_BRASS + c) as u32; }
            }
            // ---- lambda (verbatim from the YAML) ----
            if let Some(i) = (|| -> Option<u8> {
                // The thing a streamed panel structurally cannot do: when the server
                // dies it keeps showing a frame that looks perfectly correct. This one
                // marks the corner instead.
                if let Some(c) = stale_marker(ctx, x, y, 30_000, 6, ALERT) { return Some(c); }
                
                // A border, rejected on the row first so the ~97% of pixels that are
                // nowhere near an edge cost one comparison.
                if edge || x < 2 || x >= ctx.w - 2 {
                    return Some(RAMP_SLATE + 10);
                }
                None
            })() { return i as u32; }
            BG as u32
        })();
    }
}

/// Scroll bands from `scroll:` in the YAML: (y0, y1, speed, rightward).
pub const SCROLL_HELLO: &[(usize, usize, usize, bool)] = &[
];

/// No `display.dynamic` declared: every row is treated as changing.
pub const DYNAMIC_HELLO: Option<(usize, usize)> = None;

/// Per-frame palette from `palette:` in the YAML. 256 words a frame --
/// the cheapest animation available, and flat in wall size.
pub fn palette_hello(ctx: &Ctx, i: usize) -> u32 {
    let _ = (&ctx, i);
    let f = ctx.frame as usize;
    match i {
        // The white ramp breathes. Nothing is redrawn to make this happen.
        16..=31 => {
            let cov = (i - 16) as u32;
            let lift = 150 + (sin64(f / 8) + 256) as u32 * 100 / 512;
            rgb((lift * cov / 15) as u8, (lift * cov / 15) as u8, (lift * cov / 15) as u8)
        }
        _ => crate::program::palette_default(i),
    }
}

/// Generated from panels/railboard.yaml -- edit the YAML, not this.
///
/// ONE function per row, in two halves: a prologue of everything that
/// depends on y but not x, then the pixel loop. That split is the whole
/// reason a program is affordable, and it is why the prologue is inlined
/// here rather than living in a helper -- a `lambda` widget's own `row:`
/// block is spliced into it, and its locals have to be visible to the
/// loop body below.
///
/// The band test, the `when:` guard, the value lookup and the centring
/// width() all depend only on the row, but were once evaluated inside the
/// pixel loop, per widget, for all 16384 pixels. `ctx.val()` is a linear
/// scan of the value table, and a four-page program asks `page == 'N'` in
/// every widget, so a pixel paid for ~24 of them. Measured on
/// dashboard-home: 20268 cycles per pixel, against 11 for a bare store.
pub fn render_railboard(ctx: &Ctx, y: usize, x0: usize, row: &mut [u32]) {
    let _ = (&ctx, y, x0);
    #[allow(non_snake_case)] let FONT_HEAD = &FONT_DEJAVUSANS_11;
    #[allow(non_upper_case_globals)] const FONT_HEAD_LH: usize = FONT_DEJAVUSANS_11_LH;
    #[allow(non_snake_case)] let FONT_MONO = &FONT_DEJAVUSANSMONOBOLD_14;
    #[allow(non_upper_case_globals)] const FONT_MONO_LH: usize = FONT_DEJAVUSANSMONOBOLD_14_LH;
    #[allow(non_snake_case)] let FONT_SMALL = &FONT_DEJAVUSANSMONOBOLD_11;
    #[allow(non_upper_case_globals)] const FONT_SMALL_LH: usize = FONT_DEJAVUSANSMONOBOLD_11_LH;
    // value 'sys'
    let g_0 = y >= 0 && y < 0 + FONT_HEAD_LH;
    let (s_0, o_0, e_0) = if g_0 {
        let s = ctx.val("sys");
        let tw = FONT_HEAD.width(s);
        let ox = 2;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'hhmm'
    let g_1 = y >= 2 && y < 2 + FONT_SMALL_LH;
    let (s_1, o_1, e_1) = if g_1 {
        let s = ctx.val("hhmm");
        let tw = FONT_SMALL.width(s);
        let ox = 92;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'r0a'
    let g_2 = y >= 18 && y < 18 + FONT_SMALL_LH;
    let (s_2, o_2, e_2) = if g_2 {
        let s = ctx.val("r0a");
        let tw = FONT_SMALL.width(s);
        let ox = 1;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'r1a'
    let g_3 = y >= 35 && y < 35 + FONT_SMALL_LH;
    let (s_3, o_3, e_3) = if g_3 {
        let s = ctx.val("r1a");
        let tw = FONT_SMALL.width(s);
        let ox = 1;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'r2a'
    let g_4 = y >= 69 && y < 69 + FONT_SMALL_LH;
    let (s_4, o_4, e_4) = if g_4 {
        let s = ctx.val("r2a");
        let tw = FONT_SMALL.width(s);
        let ox = 1;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'r3a'
    let g_5 = y >= 86 && y < 86 + FONT_SMALL_LH;
    let (s_5, o_5, e_5) = if g_5 {
        let s = ctx.val("r3a");
        let tw = FONT_SMALL.width(s);
        let ox = 1;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'r0c'
    let g_6 = y >= 18 && y < 18 + FONT_SMALL_LH;
    let (s_6, o_6, e_6) = if g_6 {
        let s = ctx.val("r0c");
        let tw = FONT_SMALL.width(s);
        let ox = 102;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'r1c'
    let g_7 = y >= 35 && y < 35 + FONT_SMALL_LH;
    let (s_7, o_7, e_7) = if g_7 {
        let s = ctx.val("r1c");
        let tw = FONT_SMALL.width(s);
        let ox = 102;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'r2c'
    let g_8 = y >= 69 && y < 69 + FONT_SMALL_LH;
    let (s_8, o_8, e_8) = if g_8 {
        let s = ctx.val("r2c");
        let tw = FONT_SMALL.width(s);
        let ox = 102;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'r3c'
    let g_9 = y >= 86 && y < 86 + FONT_SMALL_LH;
    let (s_9, o_9, e_9) = if g_9 {
        let s = ctx.val("r3c");
        let tw = FONT_SMALL.width(s);
        let ox = 102;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'foot'
    let g_10 = y >= 110 && y < 110 + FONT_SMALL_LH;
    let (s_10, o_10, e_10) = if g_10 {
        let s = ctx.val("foot");
        let tw = FONT_SMALL.width(s);
        let ox = 2;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // ---- lambda row: prologue (verbatim) ----
    let (band, band_top) = match y {
        16..=32 => (0usize, 16usize),
        33..=49 => (1, 33),
        67..=83 => (2, 67),
        84..=100 => (3, 84),
        _ => (9, 0),
    };
    let dest: &str = match band {
        0 => ctx.val("r0b"), 1 => ctx.val("r1b"),
        2 => ctx.val("r2b"), 3 => ctx.val("r3b"),
        _ => "",
    };
    // Decided ONCE per row, not per pixel: does this name fit its column?
    // `width()` walks the string, which is exactly the kind of work the
    // per-pixel rule forbids -- and exactly what a row prologue is for.
    let dest_w = if band != 9 { FONT_MONO.width(dest) } else { 0 };
    let scrolls = dest_w > 56;
    // SCROLL FROM THE CLOCK, NOT FROM THE FRAME COUNTER.
    //
    // `ctx.frame` is the obvious source and it is wrong here: the scroll
    // itself is what drags the frame rate down (30 fps static, 13 fps with
    // this band moving), so a per-frame step makes the speed a function of
    // how much work the speed is causing. At `frame >> 1` the names crawled
    // at ~6 px/s and a padded name took half a minute to come round -- the
    // column read as empty for most of a page.
    //
    // `time_ms` is uptime in milliseconds and independent of all that:
    // /40 is 25 px/s whatever the card is managing, and the divide is by a
    // constant so the compiler strength-reduces it.
    let vx0 = (ctx.time_ms / 40) as usize;
    let stale = ctx.stale_ms() > 120_000;
    for (i, p) in row.iter_mut().enumerate() {
        let x = x0 + i;
        *p = (|| -> u32 {
            if g_0 && x >= o_0 && x < e_0 {
                if let Some(c) = FONT_HEAD.cover_at(s_0, x, y, o_0, 0) { return (RAMP_BRASS + c) as u32; }
            }
            if g_1 && x >= o_1 && x < e_1 {
                if let Some(c) = FONT_SMALL.cover_at(s_1, x, y, o_1, 2) { return (RAMP_SLATE + c) as u32; }
            }
            if g_2 && x >= o_2 && x < e_2 {
                if let Some(c) = FONT_SMALL.cover_at(s_2, x, y, o_2, 18) { return (RAMP_WHITE + c) as u32; }
            }
            if g_3 && x >= o_3 && x < e_3 {
                if let Some(c) = FONT_SMALL.cover_at(s_3, x, y, o_3, 35) { return (RAMP_WHITE + c) as u32; }
            }
            if g_4 && x >= o_4 && x < e_4 {
                if let Some(c) = FONT_SMALL.cover_at(s_4, x, y, o_4, 69) { return (RAMP_WHITE + c) as u32; }
            }
            if g_5 && x >= o_5 && x < e_5 {
                if let Some(c) = FONT_SMALL.cover_at(s_5, x, y, o_5, 86) { return (RAMP_WHITE + c) as u32; }
            }
            if g_6 && x >= o_6 && x < e_6 {
                if let Some(c) = FONT_SMALL.cover_at(s_6, x, y, o_6, 18) { return (RAMP_SLATE + c) as u32; }
            }
            if g_7 && x >= o_7 && x < e_7 {
                if let Some(c) = FONT_SMALL.cover_at(s_7, x, y, o_7, 35) { return (RAMP_SLATE + c) as u32; }
            }
            if g_8 && x >= o_8 && x < e_8 {
                if let Some(c) = FONT_SMALL.cover_at(s_8, x, y, o_8, 69) { return (RAMP_SLATE + c) as u32; }
            }
            if g_9 && x >= o_9 && x < e_9 {
                if let Some(c) = FONT_SMALL.cover_at(s_9, x, y, o_9, 86) { return (RAMP_SLATE + c) as u32; }
            }
            if g_10 && x >= o_10 && x < e_10 {
                if let Some(c) = FONT_SMALL.cover_at(s_10, x, y, o_10, 110) { return (RAMP_SLATE + c) as u32; }
            }
            // ---- lambda (verbatim from the YAML) ----
            if let Some(i) = (|| -> Option<u8> {
                // The destination, hard-clipped to its column. THIS is the clip a
                // `value` widget does not have: it is guarded by its own string width,
                // so a long name would run straight through the countdown.
                if band != 9 && x >= 41 && x < 97 && !dest.is_empty() {
                    if scrolls {
                        // The name marches left and WRAPS -- the host pads it with a
                        // few trailing spaces so the wrap reads as a gap rather than as
                        // one word running into itself.
                        if let Some(c) = FONT_MONO.cover_scroll(dest, (x - 41) + vx0, y, band_top) {
                            return Some(RAMP_BRASS + c);
                        }
                    } else if let Some(c) = FONT_MONO.cover_at(dest, x, y, 41, band_top) {
                        return Some(RAMP_BRASS + c);
                    }
                }
                
                // Told-you-so marker: the thing a streamed card structurally cannot do.
                // Two minutes, because the Amtrak feed is pushed every two minutes by
                // design and a shorter window would cry wolf on every Amtrak page.
                if stale && y < 6 && x >= ctx.w - 6 { return Some(ALERT); }
                
                // The seam. A 1px rule ON the boundary reads as intentional; without it
                // the gap between the two modules reads as a fault.
                if y == 63 && x >= 2 && x < ctx.w - 2 { return Some(RAMP_SLATE + 2); }
                None
            })() { return i as u32; }
            BG as u32
        })();
    }
}

/// Scroll bands from `scroll:` in the YAML: (y0, y1, speed, rightward).
pub const SCROLL_RAILBOARD: &[(usize, usize, usize, bool)] = &[
];

/// Rows that change every frame, from `display.dynamic` in the YAML.
pub const DYNAMIC_RAILBOARD: Option<(usize, usize)> = Some((16, 102));

/// Per-frame palette from `palette:` in the YAML. 256 words a frame --
/// the cheapest animation available, and flat in wall size.
pub fn palette_railboard(ctx: &Ctx, i: usize) -> u32 {
    let _ = (&ctx, i);
    match i {
        16..=31 => { let c = (i - 16) as u32;
                     rgb((0xe8 * c / 15) as u8, (0xed * c / 15) as u8, (0xf5 * c / 15) as u8) }
        32..=47 => { let c = (i - 32) as u32;
                     rgb((0xc9 * c / 15) as u8, (0xa8 * c / 15) as u8, (0x4c * c / 15) as u8) }
        48..=63 => { let c = (i - 48) as u32;
                     rgb((0x88 * c / 15) as u8, (0x99 * c / 15) as u8, (0xaa * c / 15) as u8) }
        _ => crate::program::palette_default(i),
    }
}

/// Generated from panels/dashboard-home.yaml -- edit the YAML, not this.
///
/// ONE function per row, in two halves: a prologue of everything that
/// depends on y but not x, then the pixel loop. That split is the whole
/// reason a program is affordable, and it is why the prologue is inlined
/// here rather than living in a helper -- a `lambda` widget's own `row:`
/// block is spliced into it, and its locals have to be visible to the
/// loop body below.
///
/// The band test, the `when:` guard, the value lookup and the centring
/// width() all depend only on the row, but were once evaluated inside the
/// pixel loop, per widget, for all 16384 pixels. `ctx.val()` is a linear
/// scan of the value table, and a four-page program asks `page == 'N'` in
/// every widget, so a pixel paid for ~24 of them. Measured on
/// dashboard-home: 20268 cycles per pixel, against 11 for a bare store.
pub fn render_dashboard_home(ctx: &Ctx, y: usize, x0: usize, row: &mut [u32]) {
    let _ = (&ctx, y, x0);
    #[allow(non_snake_case)] let FONT_BIG = &FONT_DEJAVUSANS_30;
    #[allow(non_upper_case_globals)] const FONT_BIG_LH: usize = FONT_DEJAVUSANS_30_LH;
    #[allow(non_snake_case)] let FONT_CLOCK = &FONT_DEJAVUSANS_36;
    #[allow(non_upper_case_globals)] const FONT_CLOCK_LH: usize = FONT_DEJAVUSANS_36_LH;
    #[allow(non_snake_case)] let FONT_MID = &FONT_DEJAVUSANS_20;
    #[allow(non_upper_case_globals)] const FONT_MID_LH: usize = FONT_DEJAVUSANS_20_LH;
    #[allow(non_snake_case)] let FONT_SMALL = &FONT_DEJAVUSANS_13;
    #[allow(non_upper_case_globals)] const FONT_SMALL_LH: usize = FONT_DEJAVUSANS_13_LH;
    let v_page = ctx.val("page");
    // text 'DASHBOARD'
    let g_0 = y >= 1 && y < 1 + FONT_SMALL_LH && (v_page == "0");
    let (s_0, o_0, e_0) = if g_0 {
        let s = "DASHBOARD";
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'hhmm'
    let g_1 = y >= 9 && y < 9 + FONT_CLOCK_LH && (v_page == "0");
    let (s_1, o_1, e_1) = if g_1 {
        let s = ctx.val("hhmm");
        let tw = FONT_CLOCK.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'date'
    let g_2 = y >= 42 && y < 42 + FONT_SMALL_LH && (v_page == "0");
    let (s_2, o_2, e_2) = if g_2 {
        let s = ctx.val("date");
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'OUTSIDE'
    let g_3 = y >= 66 && y < 66 + FONT_SMALL_LH && (v_page == "0");
    let (s_3, o_3, e_3) = if g_3 {
        let s = "OUTSIDE";
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    let mut b_4 = [0u8; 48];
    // value 'temp'
    let g_4 = y >= 80 && y < 80 + FONT_BIG_LH && (v_page == "0");
    let (s_4, o_4, e_4) = if g_4 {
        let s = join3(&mut b_4, "", ctx.val("temp"), "°");
        let tw = FONT_BIG.width(s);
        let ox = 6;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'cond'
    let g_5 = y >= 88 && y < 88 + FONT_SMALL_LH && (v_page == "0");
    let (s_5, o_5, e_5) = if g_5 {
        let s = ctx.val("cond");
        let tw = FONT_SMALL.width(s);
        let ox = 76;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    let mut b_6 = [0u8; 48];
    // value 'humidity'
    let g_6 = y >= 107 && y < 107 + FONT_SMALL_LH && (v_page == "0");
    let (s_6, o_6, e_6) = if g_6 {
        let s = join3(&mut b_6, "HUMIDITY ", ctx.val("humidity"), "%");
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'SECURITY'
    let g_7 = y >= 1 && y < 1 + FONT_SMALL_LH && (v_page == "1");
    let (s_7, o_7, e_7) = if g_7 {
        let s = "SECURITY";
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'DOORS'
    let g_8 = y >= 20 && y < 20 + FONT_SMALL_LH && (v_page == "1");
    let (s_8, o_8, e_8) = if g_8 {
        let s = "DOORS";
        let tw = FONT_SMALL.width(s);
        let ox = 6;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'doors'
    let g_9 = y >= 20 && y < 20 + FONT_SMALL_LH && (v_page == "1");
    let (s_9, o_9, e_9) = if g_9 {
        let s = ctx.val("doors");
        let tw = FONT_SMALL.width(s);
        let ox = 100;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'WINDOWS'
    let g_10 = y >= 38 && y < 38 + FONT_SMALL_LH && (v_page == "1");
    let (s_10, o_10, e_10) = if g_10 {
        let s = "WINDOWS";
        let tw = FONT_SMALL.width(s);
        let ox = 6;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'windows'
    let g_11 = y >= 38 && y < 38 + FONT_SMALL_LH && (v_page == "1");
    let (s_11, o_11, e_11) = if g_11 {
        let s = ctx.val("windows");
        let tw = FONT_SMALL.width(s);
        let ox = 100;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'GARAGE'
    let g_12 = y >= 66 && y < 66 + FONT_SMALL_LH && (v_page == "1");
    let (s_12, o_12, e_12) = if g_12 {
        let s = "GARAGE";
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'OPEN'
    let g_13 = y >= 86 && y < 86 + FONT_SMALL_LH && (v_page == "1");
    let (s_13, o_13, e_13) = if g_13 {
        let s = "OPEN";
        let tw = FONT_SMALL.width(s);
        let ox = 6;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'garage'
    let g_14 = y >= 86 && y < 86 + FONT_SMALL_LH && (v_page == "1");
    let (s_14, o_14, e_14) = if g_14 {
        let s = ctx.val("garage");
        let tw = FONT_SMALL.width(s);
        let ox = 100;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'UNLOCKED'
    let g_15 = y >= 104 && y < 104 + FONT_SMALL_LH && (v_page == "1");
    let (s_15, o_15, e_15) = if g_15 {
        let s = "UNLOCKED";
        let tw = FONT_SMALL.width(s);
        let ox = 6;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'unlocked'
    let g_16 = y >= 104 && y < 104 + FONT_SMALL_LH && (v_page == "1");
    let (s_16, o_16, e_16) = if g_16 {
        let s = ctx.val("unlocked");
        let tw = FONT_SMALL.width(s);
        let ox = 100;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'POWER kW'
    let g_17 = y >= 1 && y < 1 + FONT_SMALL_LH && (v_page == "2");
    let (s_17, o_17, e_17) = if g_17 {
        let s = "POWER kW";
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'power'
    let g_18 = y >= 16 && y < 16 + FONT_BIG_LH && (v_page == "2");
    let (s_18, o_18, e_18) = if g_18 {
        let s = ctx.val("power");
        let tw = FONT_BIG.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'TOTAL'
    let g_19 = y >= 46 && y < 46 + FONT_SMALL_LH && (v_page == "2");
    let (s_19, o_19, e_19) = if g_19 {
        let s = "TOTAL";
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'RECENT LOAD'
    let g_20 = y >= 66 && y < 66 + FONT_SMALL_LH && (v_page == "2");
    let (s_20, o_20, e_20) = if g_20 {
        let s = "RECENT LOAD";
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'IRRIGATION'
    let g_21 = y >= 1 && y < 1 + FONT_SMALL_LH && (v_page == "3");
    let (s_21, o_21, e_21) = if g_21 {
        let s = "IRRIGATION";
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    let mut b_22 = [0u8; 48];
    // value 'gallons'
    let g_22 = y >= 12 && y < 12 + FONT_BIG_LH && (v_page == "3");
    let (s_22, o_22, e_22) = if g_22 {
        let s = join3(&mut b_22, "", ctx.val("gallons"), " gal");
        let tw = FONT_BIG.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'TODAY'
    let g_23 = y >= 47 && y < 47 + FONT_SMALL_LH && (v_page == "3");
    let (s_23, o_23, e_23) = if g_23 {
        let s = "TODAY";
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // text 'NEXT'
    let g_24 = y >= 66 && y < 66 + FONT_SMALL_LH && (v_page == "3");
    let (s_24, o_24, e_24) = if g_24 {
        let s = "NEXT";
        let tw = FONT_SMALL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // value 'nextzone'
    let g_25 = y >= 84 && y < 84 + FONT_MID_LH && (v_page == "3");
    let (s_25, o_25, e_25) = if g_25 {
        let s = ctx.val("nextzone");
        let tw = FONT_MID.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    let mut b_26 = [0u8; 48];
    // value 'zones'
    let g_26 = y >= 106 && y < 106 + FONT_SMALL_LH && (v_page == "3");
    let (s_26, o_26, e_26) = if g_26 {
        let s = join3(&mut b_26, "", ctx.val("zones"), " ZONES");
        let tw = FONT_SMALL.width(s);
        let ox = 8;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    let mut b_27 = [0u8; 48];
    // value 'running'
    let g_27 = y >= 106 && y < 106 + FONT_SMALL_LH && (v_page == "3");
    let (s_27, o_27, e_27) = if g_27 {
        let s = join3(&mut b_27, "RUN ", ctx.val("running"), "");
        let tw = FONT_SMALL.width(s);
        let ox = 86;
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // ---- lambda row: prologue (verbatim) ----
    let trace_row = y >= 84 && y < 119 && v_page == "2";
    let hist: &[u8] = if trace_row { ctx.val("hist").as_bytes() } else { &[] };
    let dots_row = y >= 122 && y < 125;
    let dot_page = if dots_row { ctx.int("page").unwrap_or(0) as usize } else { 0 };
    let dot_slot = ctx.w / 2 - 14;
    let stale = ctx.stale_ms() > 30_000;
    for (i, p) in row.iter_mut().enumerate() {
        let x = x0 + i;
        *p = (|| -> u32 {
            if g_0 && x >= o_0 && x < e_0 {
                if let Some(c) = FONT_SMALL.cover_at(s_0, x, y, o_0, 1) { return (RAMP_SLATE + c) as u32; }
            }
            if g_1 && x >= o_1 && x < e_1 {
                if let Some(c) = FONT_CLOCK.cover_at(s_1, x, y, o_1, 9) { return (RAMP_WHITE + c) as u32; }
            }
            if g_2 && x >= o_2 && x < e_2 {
                if let Some(c) = FONT_SMALL.cover_at(s_2, x, y, o_2, 42) { return (RAMP_SLATE + c) as u32; }
            }
            if g_3 && x >= o_3 && x < e_3 {
                if let Some(c) = FONT_SMALL.cover_at(s_3, x, y, o_3, 66) { return (RAMP_SLATE + c) as u32; }
            }
            if g_4 && x >= o_4 && x < e_4 {
                if let Some(c) = FONT_BIG.cover_at(s_4, x, y, o_4, 80) { return (RAMP_BRASS + c) as u32; }
            }
            if g_5 && x >= o_5 && x < e_5 {
                if let Some(c) = FONT_SMALL.cover_at(s_5, x, y, o_5, 88) { return (RAMP_WHITE + c) as u32; }
            }
            if g_6 && x >= o_6 && x < e_6 {
                if let Some(c) = FONT_SMALL.cover_at(s_6, x, y, o_6, 107) { return (RAMP_SLATE + c) as u32; }
            }
            if g_7 && x >= o_7 && x < e_7 {
                if let Some(c) = FONT_SMALL.cover_at(s_7, x, y, o_7, 1) { return (RAMP_SLATE + c) as u32; }
            }
            if g_8 && x >= o_8 && x < e_8 {
                if let Some(c) = FONT_SMALL.cover_at(s_8, x, y, o_8, 20) { return (RAMP_WHITE + c) as u32; }
            }
            if g_9 && x >= o_9 && x < e_9 {
                if let Some(c) = FONT_SMALL.cover_at(s_9, x, y, o_9, 20) { return (RAMP_WHITE + c) as u32; }
            }
            if g_10 && x >= o_10 && x < e_10 {
                if let Some(c) = FONT_SMALL.cover_at(s_10, x, y, o_10, 38) { return (RAMP_WHITE + c) as u32; }
            }
            if g_11 && x >= o_11 && x < e_11 {
                if let Some(c) = FONT_SMALL.cover_at(s_11, x, y, o_11, 38) { return (RAMP_WHITE + c) as u32; }
            }
            if g_12 && x >= o_12 && x < e_12 {
                if let Some(c) = FONT_SMALL.cover_at(s_12, x, y, o_12, 66) { return (RAMP_SLATE + c) as u32; }
            }
            if g_13 && x >= o_13 && x < e_13 {
                if let Some(c) = FONT_SMALL.cover_at(s_13, x, y, o_13, 86) { return (RAMP_WHITE + c) as u32; }
            }
            if g_14 && x >= o_14 && x < e_14 {
                if let Some(c) = FONT_SMALL.cover_at(s_14, x, y, o_14, 86) { return (RAMP_WHITE + c) as u32; }
            }
            if g_15 && x >= o_15 && x < e_15 {
                if let Some(c) = FONT_SMALL.cover_at(s_15, x, y, o_15, 104) { return (RAMP_BRASS + c) as u32; }
            }
            if g_16 && x >= o_16 && x < e_16 {
                if let Some(c) = FONT_SMALL.cover_at(s_16, x, y, o_16, 104) { return (RAMP_BRASS + c) as u32; }
            }
            if g_17 && x >= o_17 && x < e_17 {
                if let Some(c) = FONT_SMALL.cover_at(s_17, x, y, o_17, 1) { return (RAMP_SLATE + c) as u32; }
            }
            if g_18 && x >= o_18 && x < e_18 {
                if let Some(c) = FONT_BIG.cover_at(s_18, x, y, o_18, 16) { return (RAMP_WHITE + c) as u32; }
            }
            if g_19 && x >= o_19 && x < e_19 {
                if let Some(c) = FONT_SMALL.cover_at(s_19, x, y, o_19, 46) { return (RAMP_SLATE + c) as u32; }
            }
            if g_20 && x >= o_20 && x < e_20 {
                if let Some(c) = FONT_SMALL.cover_at(s_20, x, y, o_20, 66) { return (RAMP_SLATE + c) as u32; }
            }
            if g_21 && x >= o_21 && x < e_21 {
                if let Some(c) = FONT_SMALL.cover_at(s_21, x, y, o_21, 1) { return (RAMP_SLATE + c) as u32; }
            }
            if g_22 && x >= o_22 && x < e_22 {
                if let Some(c) = FONT_BIG.cover_at(s_22, x, y, o_22, 12) { return (RAMP_WATER + c) as u32; }
            }
            if g_23 && x >= o_23 && x < e_23 {
                if let Some(c) = FONT_SMALL.cover_at(s_23, x, y, o_23, 47) { return (RAMP_SLATE + c) as u32; }
            }
            if g_24 && x >= o_24 && x < e_24 {
                if let Some(c) = FONT_SMALL.cover_at(s_24, x, y, o_24, 66) { return (RAMP_SLATE + c) as u32; }
            }
            if g_25 && x >= o_25 && x < e_25 {
                if let Some(c) = FONT_MID.cover_at(s_25, x, y, o_25, 84) { return (RAMP_WHITE + c) as u32; }
            }
            if g_26 && x >= o_26 && x < e_26 {
                if let Some(c) = FONT_SMALL.cover_at(s_26, x, y, o_26, 106) { return (RAMP_SLATE + c) as u32; }
            }
            if g_27 && x >= o_27 && x < e_27 {
                if let Some(c) = FONT_SMALL.cover_at(s_27, x, y, o_27, 106) { return (RAMP_SLATE + c) as u32; }
            }
            // ---- lambda (verbatim from the YAML) ----
            if let Some(i) = (|| -> Option<u8> {
                // Told-you-so marker: the thing a streamed panel structurally cannot do.
                if stale && y < 6 && x >= ctx.w - 6 { return Some(ALERT); }
                
                // Page dots, so the cycle is visible at a glance.
                if dots_row {
                    for p in 0..4usize {
                        let cx = dot_slot + p * 8;
                        if x >= cx && x < cx + 4 {
                            return Some(if p == dot_page { RAMP_WHITE + 12 } else { RAMP_SLATE + 4 });
                        }
                    }
                }
                
                // The power trace. One byte per sample, '0' = 0, so a column is ONE
                // index -- O(1) per pixel, which is the rule. Parsing "43.2,42.8,.."
                // here would be a frame-rate cut, not a style choice.
                if trace_row && !hist.is_empty() {
                    let col = (x * hist.len()) / ctx.w;
                    let v = hist[col].saturating_sub(b'0') as usize;
                    let lit = (v * 34 / 63).min(34);
                    if y >= 118 - lit { return Some(RAMP_BRASS + 15); }
                    if y == 118 { return Some(RAMP_SLATE + 3); }
                }
                None
            })() { return i as u32; }
            BG as u32
        })();
    }
}

/// Scroll bands from `scroll:` in the YAML: (y0, y1, speed, rightward).
pub const SCROLL_DASHBOARD_HOME: &[(usize, usize, usize, bool)] = &[
];

/// No `display.dynamic` declared: every row is treated as changing.
pub const DYNAMIC_DASHBOARD_HOME: Option<(usize, usize)> = None;

/// Per-frame palette from `palette:` in the YAML. 256 words a frame --
/// the cheapest animation available, and flat in wall size.
pub fn palette_dashboard_home(ctx: &Ctx, i: usize) -> u32 {
    let _ = (&ctx, i);
    match i {
        16..=31 => { let c = (i - 16) as u32;
                     rgb((0xe8 * c / 15) as u8, (0xe8 * c / 15) as u8, (0xf0 * c / 15) as u8) }
        32..=47 => { let c = (i - 32) as u32;
                     rgb((0xc9 * c / 15) as u8, (0xa8 * c / 15) as u8, (0x4c * c / 15) as u8) }
        48..=63 => { let c = (i - 48) as u32;
                     rgb((0x4a * c / 15) as u8, (0x6f * c / 15) as u8, (0xb0 * c / 15) as u8) }
        192..=207 => { let c = (i - 192) as u32;
                     rgb((0x4a * c / 15) as u8, (0x9f * c / 15) as u8, (0xd0 * c / 15) as u8) }
        _ => crate::program::palette_default(i),
    }
}

/// Generated from panels/blank.yaml -- edit the YAML, not this.
///
/// ONE function per row, in two halves: a prologue of everything that
/// depends on y but not x, then the pixel loop. That split is the whole
/// reason a program is affordable, and it is why the prologue is inlined
/// here rather than living in a helper -- a `lambda` widget's own `row:`
/// block is spliced into it, and its locals have to be visible to the
/// loop body below.
///
/// The band test, the `when:` guard, the value lookup and the centring
/// width() all depend only on the row, but were once evaluated inside the
/// pixel loop, per widget, for all 16384 pixels. `ctx.val()` is a linear
/// scan of the value table, and a four-page program asks `page == 'N'` in
/// every widget, so a pixel paid for ~24 of them. Measured on
/// dashboard-home: 20268 cycles per pixel, against 11 for a bare store.
pub fn render_blank(ctx: &Ctx, y: usize, x0: usize, row: &mut [u32]) {
    let _ = (&ctx, y, x0);
    for (i, p) in row.iter_mut().enumerate() {
        let x = x0 + i;
        *p = (|| -> u32 {
            // ---- lambda (verbatim from the YAML) ----
            if let Some(i) = (|| -> Option<u8> {
                Some(BG)
            })() { return i as u32; }
            BG as u32
        })();
    }
}

/// Scroll bands from `scroll:` in the YAML: (y0, y1, speed, rightward).
pub const SCROLL_BLANK: &[(usize, usize, usize, bool)] = &[
];

/// No `display.dynamic` declared: every row is treated as changing.
pub const DYNAMIC_BLANK: Option<(usize, usize)> = None;

/// Generated from panels/ticker.yaml -- edit the YAML, not this.
///
/// ONE function per row, in two halves: a prologue of everything that
/// depends on y but not x, then the pixel loop. That split is the whole
/// reason a program is affordable, and it is why the prologue is inlined
/// here rather than living in a helper -- a `lambda` widget's own `row:`
/// block is spliced into it, and its locals have to be visible to the
/// loop body below.
///
/// The band test, the `when:` guard, the value lookup and the centring
/// width() all depend only on the row, but were once evaluated inside the
/// pixel loop, per widget, for all 16384 pixels. `ctx.val()` is a linear
/// scan of the value table, and a four-page program asks `page == 'N'` in
/// every widget, so a pixel paid for ~24 of them. Measured on
/// dashboard-home: 20268 cycles per pixel, against 11 for a bare store.
pub fn render_ticker(ctx: &Ctx, y: usize, x0: usize, row: &mut [u32]) {
    let _ = (&ctx, y, x0);
    #[allow(non_snake_case)] let FONT_LABEL = &FONT_DEJAVUSANS_13;
    #[allow(non_upper_case_globals)] const FONT_LABEL_LH: usize = FONT_DEJAVUSANS_13_LH;
    #[allow(non_snake_case)] let FONT_TICK = &FONT_DEJAVUSANSMONOBOLD_26;
    #[allow(non_upper_case_globals)] const FONT_TICK_LH: usize = FONT_DEJAVUSANSMONOBOLD_26_LH;
    // value 'hhmm'
    let g_0 = y >= 44 && y < 44 + FONT_TICK_LH;
    let (s_0, o_0, e_0) = if g_0 {
        let s = ctx.val("hhmm");
        let tw = FONT_TICK.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    let mut b_1 = [0u8; 48];
    // value 'temp'
    let g_1 = y >= 72 && y < 72 + FONT_LABEL_LH;
    let (s_1, o_1, e_1) = if g_1 {
        let s = join3(&mut b_1, "OUTSIDE ", ctx.val("temp"), "°");
        let tw = FONT_LABEL.width(s);
        let ox = if ctx.w > tw { (ctx.w - tw) / 2 } else { 2 };
        (s, ox, ox + tw + 4)
    } else { ("", 0usize, 0usize) };
    // ---- lambda row: prologue (verbatim) ----
    let top_row = y >= 8 && y < 42;
    let bot_row = y >= 88 && y < 122;
    let ring_row = y < 3 || y >= ctx.h - 3;
    let ybulb = y >> 3;
    for (i, p) in row.iter_mut().enumerate() {
        let x = x0 + i;
        *p = (|| -> u32 {
            if g_0 && x >= o_0 && x < e_0 {
                if let Some(c) = FONT_TICK.cover_at(s_0, x, y, o_0, 44) { return (RAMP_WHITE + c) as u32; }
            }
            if g_1 && x >= o_1 && x < e_1 {
                if let Some(c) = FONT_LABEL.cover_at(s_1, x, y, o_1, 72) { return (RAMP_BRASS + c) as u32; }
            }
            // ---- lambda (verbatim from the YAML) ----
            if let Some(i) = (|| -> Option<u8> {
                // Built only when a value actually LANDS -- about once every ten
                // seconds, not once per frame. Padded to a power-of-two length so
                // cover_scroll's message index is a mask rather than a third software
                // division; riscv32i has no divide instruction.
                fn top(ctx: &Ctx, m: &mut Msg) {
                    use core::fmt::Write;
                    // Padding is for a CONSTANT PERIOD, not for length: cover_scroll
                    // wraps modulo len*advance, so a message that changed length would
                    // make the tape jump. But pad far past the text and the padding is
                    // what you see -- 38 characters padded to 64 left 26 spaces, a
                    // 416px gap in a 1024px period, so the tape read as empty for
                    // fifteen seconds out of every thirty-six. Fill the period.
                    let _ = write!(m, "*** DASHBOARD NEW YORK *** OUTSIDE {:>3.3}F *** {:<11.11} *** ",
                                   ctx.val("temp"), ctx.val("cond"));
                    m.pad_to(64);
                }
                fn bot(ctx: &Ctx, m: &mut Msg) {
                    use core::fmt::Write;
                    let _ = write!(m, "+++ HOUSE LOAD {:>6.6} kW +++ THE TIME IS {:>5.5} +++ ON AIR +++ ",
                                   ctx.val("power"), ctx.val("hhmm"));
                    m.pad_to(64);
                }
                
                if top_row {
                    if let Some(c) = scroll_message(ctx, &FONT_TICK, top, x, y, 10, 1, RAMP_WHITE) {
                        return Some(c);
                    }
                    return Some(RAMP_SLATE + ((y - 8) * 15 / 34) as u8);
                }
                if bot_row {
                    if let Some(c) = scroll_message_rev(ctx, &FONT_TICK, bot, x, y, 90, 1, RAMP_WHITE) {
                        return Some(c);
                    }
                    return Some(RAMP_SLATE + ((121 - y) * 15 / 34) as u8);
                }
                
                // The bulb ring. A pixel takes the index of the BULB it belongs to and
                // the palette does the chasing -- so the frame is alive for no writes.
                if ring_row || x < 3 || x >= ctx.w - 3 {
                    return Some(RAMP_BULB + (((x >> 3) + ybulb) & 15) as u8);
                }
                
                // THE ZOOM, and it costs nothing.
                //
                // Each pixel takes the index of the RING it sits on -- Chebyshev
                // distance from the centre, which is two abs_diffs and a max. A squared
                // radius would be two multiplies and a compare per pixel; this is three
                // single-cycle operations and looks better here anyway. Rotating those entries in
                // the palette makes the rings rush outward, and dropping their
                // brightness together makes the whole sign flash.
                //
                // So the attract sequence -- rings zooming, colour cycling, the big
                // strobe every eight seconds -- is 256 words a frame and NOT ONE pixel
                // write. That is the argument for program mode in one line.
                let d = x.abs_diff(ctx.w / 2).max(y.abs_diff(ctx.h / 2));
                Some(RAINBOW + ((d << 2) & 127) as u8)
            })() { return i as u32; }
            BG as u32
        })();
    }
}

/// Scroll bands from `scroll:` in the YAML: (y0, y1, speed, rightward).
pub const SCROLL_TICKER: &[(usize, usize, usize, bool)] = &[
    (8, 42, 1, false),
    (88, 122, 1, true),
];

/// Rows that change every frame, from `display.dynamic` in the YAML.
pub const DYNAMIC_TICKER: Option<(usize, usize)> = Some((0, 0));

/// Per-frame palette from `palette:` in the YAML. 256 words a frame --
/// the cheapest animation available, and flat in wall size.
pub fn palette_ticker(ctx: &Ctx, i: usize) -> u32 {
    let _ = (&ctx, i);
    let f = ctx.frame as usize;
    // THE BEAT. ~8 seconds at 30 fps: a long calm stretch, then a two-second
    // blast. Derived from the frame counter, so it needs no state and survives a
    // program restart mid-cycle.
    let beat = f % 240;
    let blast = beat >= 180;
    // How hard the blast hits. NOT 255: a HUB75 module at this pitch is painfully
    // bright at full scale, and the gateware applies gamma downstream so the top
    // of the range is where most of the perceived output lives. ~60% reads as a
    // bright flash across a room without being unpleasant to sit near.
    const HOT: u32 = 150;
    // And it strobes on one frame in four rather than two, so it reads as a
    // flicker rather than a stutter.
    let strobe = f & 3 == 0;
    // Six-segment hue wheel, 0..127 -> rgb. No float and no divide beyond the
    // constants; this runs 256 times a frame, not once per pixel.
    fn wheel(t: usize) -> (u32, u32, u32) {
        let t = t & 127;
        let seg = t * 6 / 128;
        let k = (((t * 6) % 128) * 255 / 128) as u32;
        match seg {
            0 => (255, k, 0),
            1 => (255 - k, 255, 0),
            2 => (0, 255, k),
            3 => (0, 255 - k, 255),
            4 => (k, 0, 255),
            _ => (255, 0, 255 - k),
        }
    }
    match i {
        // 16..31 -- tape text AND the clock. Hue runs ALONG the run, so the
        // colour travels through the letters while the letters travel past.
        16..=31 => {
            let cov = (i - 16) as u32;
            // During the blast the type goes hard white and strobes with the
            // field, so the whole sign pulses as one thing.
            if blast && strobe {
                // The type stays a little hotter than the rest -- it is what the
                // eye lands on -- but still well under full scale.
                let w = HOT + 40;
                rgb((w * cov / 15) as u8, (w * cov / 15) as u8, (w * cov / 15) as u8)
            } else {
                let (r, g, b) = wheel((i - 16) * 5 + f * if blast { 12 } else { 3 });
                rgb((r * cov / 15) as u8, (g * cov / 15) as u8, (b * cov / 15) as u8)
            }
        }
        // 32..47 -- the temperature, pulsing white-hot to amber.
        32..=47 => {
            let cov = (i - 32) as u32;
            let beat = (176 + sin64(f / 2) * 80 / 256) as u32;
            rgb((beat * cov / 15) as u8, ((beat * 3 / 4) * cov / 15) as u8, ((beat / 3) * cov / 15) as u8)
        }
        // 48..63 -- the tape grounds, breathing. The pixels holding these
        // indices are never rewritten, so this motion is free.
        48..=63 => {
            let d = (i - 48) as u32;
            // The grounds fire with everything else, so the blast is the WHOLE
            // sign going off rather than a bright patch in the middle of it.
            if blast && strobe {
                rgb((HOT * d / 15) as u8, (HOT * d / 15) as u8, (HOT * d / 15) as u8)
            } else {
                let pulse = 30 + (sin64(f / 4 + (i - 48)) + 256) as u32 * 50 / 512;
                rgb((pulse * d / 46) as u8, (pulse * d / 30) as u8, (pulse * d / 20) as u8)
            }
        }
        // 64..191 -- the rings. THE ATTRACT SEQUENCE LIVES HERE.
        //
        // An eight-second beat: seven seconds of rings rushing outward under the
        // clock, then a two-second BLAST where they accelerate, saturate and
        // strobe. None of it writes a pixel.
        64..=191 => {
            let t = i - 64;
            if blast {
                // Rings rush four times faster and run at full brightness, with
                // the whole field flashing to white on alternate frames.
                let (r, g, b) = wheel(t + f * 8);
                if strobe { rgb(HOT as u8, HOT as u8, HOT as u8) }
                else { rgb((r * 3 / 5) as u8, (g * 3 / 5) as u8, (b * 3 / 5) as u8) }
            } else {
                // Held well down the rest of the time so the clock reads.
                let (r, g, b) = wheel(t + f * 2);
                let k = 4 + (sin64(f / 6) + 256) as u32 * 4 / 512;
                rgb((r / k) as u8, (g / k) as u8, (b / k) as u8)
            }
        }
        // 208..223 -- theatre bulbs. A bright group of three chases round the
        // sixteen phases; the rest glow dim, and the whole ring drifts in hue.
        208..=223 => {
            // Chasing normally; during the blast every bulb fires at once, on
            // alternate frames, like a theatre frame being flashed.
            let ph = (i - 208 + f / if blast { 1 } else { 2 }) & 15;
            let (r, g, b) = wheel((i - 208) * 8 + f * 4);
            if blast {
                if strobe { rgb(HOT as u8, HOT as u8, HOT as u8) }
                else { rgb((r * 3 / 5) as u8, (g * 3 / 5) as u8, (b * 3 / 5) as u8) }
            }
            // The lit bulbs ring the whole frame and are on all the time, so
            // they are what the room actually sees. Held to ~70% -- at full
            // scale they were the brightest thing on the panel by a distance.
            else if ph < 3 { rgb((r * 7 / 10) as u8, (g * 7 / 10) as u8, (b * 7 / 10) as u8) }
            else { rgb((r / 7) as u8, (g / 7) as u8, (b / 7) as u8) }
        }
        _ => crate::program::palette_default(i),
    }
}

/// Generated from panels/timessquare.yaml -- edit the YAML, not this.
///
/// ONE function per row, in two halves: a prologue of everything that
/// depends on y but not x, then the pixel loop. That split is the whole
/// reason a program is affordable, and it is why the prologue is inlined
/// here rather than living in a helper -- a `lambda` widget's own `row:`
/// block is spliced into it, and its locals have to be visible to the
/// loop body below.
///
/// The band test, the `when:` guard, the value lookup and the centring
/// width() all depend only on the row, but were once evaluated inside the
/// pixel loop, per widget, for all 16384 pixels. `ctx.val()` is a linear
/// scan of the value table, and a four-page program asks `page == 'N'` in
/// every widget, so a pixel paid for ~24 of them. Measured on
/// dashboard-home: 20268 cycles per pixel, against 11 for a bare store.
pub fn render_timessquare(ctx: &Ctx, y: usize, x0: usize, row: &mut [u32]) {
    let _ = (&ctx, y, x0);
    #[allow(non_snake_case)] let FONT_TICK = &FONT_DEJAVUSANSMONOBOLD_26;
    #[allow(non_upper_case_globals)] const FONT_TICK_LH: usize = FONT_DEJAVUSANSMONOBOLD_26_LH;
    #[allow(non_snake_case)] let ICON_STAR = &ICON_STAR_26;
    // ---- lambda row: prologue (verbatim) ----
    // Everything here happens 128 times a frame instead of 16384.
    let f = ctx.frame as usize;
    let plasma_row = PlasmaRow::new(ctx, y);
    let spin = f / 2;
    let tape_top = y >= 6 && y < 40;
    let tape_bot = y >= 90 && y < 124;
    let star_row = y.abs_diff(ctx.h / 2) <= 21;
    // The border and the stale marker only ever ink the outside. Deciding
    // that once per row means ~14000 pixels a frame stop making two calls
    // apiece to be told "not here".
    let edge_row = y < 3 || y >= ctx.h - 3;
    let stale_row = y < 6 && ctx.stale_ms() > 30_000;
    let ground_top = RAMP_SLATE + ((y.saturating_sub(6)) * 15 / 34) as u8;
    let ground_bot = RAMP_SLATE + ((123usize.saturating_sub(y)) * 15 / 34) as u8;
    for (i, p) in row.iter_mut().enumerate() {
        let x = x0 + i;
        *p = (|| -> u32 {
            // ---- lambda (verbatim from the YAML) ----
            if let Some(i) = (|| -> Option<u8> {
                fn top(ctx: &Ctx, m: &mut Msg) {
                    use core::fmt::Write;
                    let _ = write!(
                        m, "*** DASHBOARD NEW YORK *** OUTSIDE {:>3.3}F *** {:<11.11} *** ",
                        ctx.val("temp"), ctx.val("cond"),
                    );
                    // 59 characters into a 64 period. Padding sets the PERIOD, so it
                    // must be the next power of two ABOVE the text, not far above it:
                    // pad far past and the padding is what you see. This tape was 62
                    // characters padded to 128, which is 66 blank ones -- the tape read
                    // as empty most of the time.
                    m.pad_to(64);
                }
                fn bot(ctx: &Ctx, m: &mut Msg) {
                    use core::fmt::Write;
                    let _ = write!(
                        m, "+++ DOORS {:>2.2} +++ WINDOWS {:>2.2} +++ GARAGE {:>2.2} +++ UNLOCKED {:>2.2} +++ ",
                        ctx.val("doors"), ctx.val("windows"), ctx.val("garage"), ctx.val("unlocked"),
                    );
                    m.pad_to(64);
                }
                
                // The tapes are SHIFTED, not redrawn, so they may contain only the text
                // and a ground that depends on y alone -- no sparkle, no plasma, or the
                // shift would smear it along with the letters. A shift moves pixels
                // along a row, so anything constant in x survives untouched: that is
                // how a shifted tape still gets a moving background, since the ground
                // is a palette INDEX and the palette hook animates it for no writes.
                if tape_top {
                    if let Some(c) = scroll_message(ctx, &FONT_TICK, top, x, y, 8, 1, RAMP_WHITE) {
                        return Some(c);
                    }
                    return Some(ground_top);
                }
                if tape_bot {
                    if let Some(c) = scroll_message_rev(ctx, &FONT_TICK, bot, x, y, 92, 1, RAMP_WHITE) {
                        return Some(c);
                    }
                    return Some(ground_bot);
                }
                
                // The thing a streamed panel structurally cannot do: when the host dies
                // it keeps showing a frame that looks perfectly correct. This says so.
                if stale_row && x >= ctx.w - 6 { return Some(ALERT); }
                
                if let Some(c) = sparkle(ctx, x, y, 17, RAMP_WHITE) { return Some(c); }
                if edge_row || x < 3 || x >= ctx.w - 3 {
                    if let Some(c) = border_chase(ctx, x, y, 3, 3) { return Some(c); }
                }
                if star_row {
                    if let Some(c) = sprite_rotated(&ICON_STAR, x, y, ctx.w / 2, ctx.h / 2, spin, RAMP_WHITE) {
                        return Some(c);
                    }
                }
                Some(plasma_row.at(x))
            })() { return i as u32; }
            BG as u32
        })();
    }
}

/// Scroll bands from `scroll:` in the YAML: (y0, y1, speed, rightward).
pub const SCROLL_TIMESSQUARE: &[(usize, usize, usize, bool)] = &[
    (6, 40, 1, false),
    (90, 124, 1, true),
];

/// No `display.dynamic` declared: every row is treated as changing.
pub const DYNAMIC_TIMESSQUARE: Option<(usize, usize)> = None;

/// Per-frame palette from `palette:` in the YAML. 256 words a frame --
/// the cheapest animation available, and flat in wall size.
pub fn palette_timessquare(ctx: &Ctx, i: usize) -> u32 {
    let _ = (&ctx, i);
    let f = ctx.frame as usize;
    match i {
        0 => rgb(0, 0, 0),
        1..=3 => rgb(0, 0, 0),
        16..=31 => {
            let cov = (i - 16) as u32;
            let t = ((i - 16) * 6 + f * 4) & 127;
            let seg = t * 6 / 128;
            let k = (((t * 6) % 128) * 255 / 128) as u32;
            let (r, g, b) = match seg {
                0 => (255, k, 0),
                1 => (255 - k, 255, 0),
                2 => (0, 255, k),
                3 => (0, 255 - k, 255),
                4 => (k, 0, 255),
                _ => (255, 0, 255 - k),
            };
            rgb((r * cov / 15) as u8, (g * cov / 15) as u8, (b * cov / 15) as u8)
        }
        48..=63 => {
            let d = (i - 48) as u32;
            let pulse = 40 + (sin64(f / 3 + (i - 48) * 2) + 256) as u32 * 60 / 512;
            rgb((pulse * d / 40) as u8, (pulse * d / 26) as u8, (pulse * d / 18) as u8)
        }
        _ => crate::program::palette_default(i),
    }
}

/// Programs by name, so `mode: program` can select one at runtime
/// without a per-panel firmware -- marquee cannot do that (TODO item 8).
/// Every program in this firmware. One firmware carries them all and
/// the config picks which runs -- marquee cannot do per-panel firmware.
pub static PROGRAMS: [Program; 6] = [
    Program { name: "hello", row: render_hello, palette_static: false, dynamic: DYNAMIC_HELLO, scroll: SCROLL_HELLO, palette: Some(palette_hello) },
    Program { name: "railboard", row: render_railboard, palette_static: true, dynamic: DYNAMIC_RAILBOARD, scroll: SCROLL_RAILBOARD, palette: Some(palette_railboard) },
    Program { name: "dashboard-home", row: render_dashboard_home, palette_static: true, dynamic: DYNAMIC_DASHBOARD_HOME, scroll: SCROLL_DASHBOARD_HOME, palette: Some(palette_dashboard_home) },
    Program { name: "blank", row: render_blank, palette_static: false, dynamic: DYNAMIC_BLANK, scroll: SCROLL_BLANK, palette: None },
    Program { name: "ticker", row: render_ticker, palette_static: false, dynamic: DYNAMIC_TICKER, scroll: SCROLL_TICKER, palette: Some(palette_ticker) },
    Program { name: "timessquare", row: render_timessquare, palette_static: false, dynamic: DYNAMIC_TIMESSQUARE, scroll: SCROLL_TIMESSQUARE, palette: Some(palette_timessquare) },
];

pub fn by_name(n: &str) -> Option<&'static Program> {
    PROGRAMS.iter().find(|p| p.name == n)
}
