// GENERATED by tools/gen_spwm_tables.py from gateware/spwm_chips.py.
// Do not edit: edit the Python and regenerate (`./build.sh spwm-tables`).
//
// These are S-PWM driver-chip register tables. The gateware is one engine
// and the chip is data; this is that data, in the form the firmware writes
// over the chip_table CSR at boot.
//
// NOTHING HERE HAS BEEN TESTED ON HARDWARE.

/// One register row: the same address on three separate driver chips,
/// which do not have to carry the same value.
#[derive(Clone, Copy)]
pub struct Row {
    pub r: u16,
    pub g: u16,
    pub b: u16,
}

/// A chip's protocol data: the rotating registers, the wrapper slots,
/// and the three grammar bits that differ between parts.
pub struct Chip {
    pub name: &'static str,
    pub regs: &'static [Row],
    pub wrappers: &'static [Row],
    pub slots: u8,
    pub rot_slot: u8,
    pub mid_latch: bool,
    /// Register address carrying the scan row count, and its mask.
    pub scan_reg: u8,
    pub scan_mask: u8,
    /// Register address carrying output current, if this chip has one.
    pub bright_reg: u8,
    pub bright_max: u8,
    /// Scan rate the capture was taken at. A table used at a different
    /// scan rate is an extrapolation -- registers other than the scan
    /// count do change with it.
    pub capture_scan: u16,
}

pub const MAX_REGS: usize = 64;
pub const MAX_WRAPPERS: usize = 8;

// dp3364s: FalconChristmas/fpp BBShiftPanel.cpp, from hzeller issue #1821
// datasheet documents the access protocol but not the register map.
static DP3364S_REGS: [Row; 15] = [
    Row { r: 0x023f, g: 0x023f, b: 0x023f },
    Row { r: 0x033f, g: 0x033f, b: 0x033f },
    Row { r: 0x041a, g: 0x041a, b: 0x041a },
    Row { r: 0x0504, g: 0x0504, b: 0x0500 },
    Row { r: 0x0639, g: 0x0639, b: 0x0639 },
    Row { r: 0x0700, g: 0x070c, b: 0x070c },
    Row { r: 0x087f, g: 0x087f, b: 0x087f },
    Row { r: 0x0968, g: 0x096b, b: 0x0961 },
    Row { r: 0x0abe, g: 0x0abf, b: 0x0abe },
    Row { r: 0x0b28, g: 0x0b2b, b: 0x0b31 },
    Row { r: 0x0c58, g: 0x0c58, b: 0x0c58 },
    Row { r: 0x0d08, g: 0x0d12, b: 0x0d18 },
    Row { r: 0x0e08, g: 0x0e0b, b: 0x0e01 },
    Row { r: 0x0f20, g: 0x0f20, b: 0x0f20 },
    Row { r: 0x1500, g: 0x1504, b: 0x1504 },
];
static DP3364S_WRAPPERS: [Row; 0] = [];

// icnd1065: nimakolahi/hub75-icn1065 (ESP32), ICND1065_REG_VALUE
// drives ICND1065L and ICND1065S. NOT ICND1065(AP).
static ICND1065_REGS: [Row; 38] = [
    Row { r: 0x00aa, g: 0x00aa, b: 0x00aa },
    Row { r: 0x01aa, g: 0x01aa, b: 0x01aa },
    Row { r: 0x022a, g: 0x022a, b: 0x022a },
    Row { r: 0x0335, g: 0x0335, b: 0x0335 },
    Row { r: 0x0412, g: 0x0412, b: 0x0412 },
    Row { r: 0x0500, g: 0x0500, b: 0x0500 },
    Row { r: 0x0601, g: 0x0601, b: 0x0601 },
    Row { r: 0x0720, g: 0x0720, b: 0x0720 },
    Row { r: 0x0c18, g: 0x0c18, b: 0x0c18 },
    Row { r: 0x0d01, g: 0x0d01, b: 0x0d01 },
    Row { r: 0x0e86, g: 0x0e86, b: 0x0e86 },
    Row { r: 0x0f01, g: 0x0f01, b: 0x0f01 },
    Row { r: 0x1040, g: 0x1040, b: 0x1040 },
    Row { r: 0x1127, g: 0x1127, b: 0x1127 },
    Row { r: 0x1200, g: 0x1200, b: 0x1200 },
    Row { r: 0x1300, g: 0x1300, b: 0x1300 },
    Row { r: 0x1400, g: 0x1400, b: 0x1400 },
    Row { r: 0x1500, g: 0x1500, b: 0x1500 },
    Row { r: 0x1600, g: 0x1600, b: 0x1600 },
    Row { r: 0x1800, g: 0x1800, b: 0x1800 },
    Row { r: 0x1906, g: 0x1906, b: 0x1906 },
    Row { r: 0x1c60, g: 0x1c60, b: 0x1c60 },
    Row { r: 0x1dca, g: 0x1dca, b: 0x1dca },
    Row { r: 0x1e73, g: 0x1e73, b: 0x1e73 },
    Row { r: 0x1f00, g: 0x1f00, b: 0x1f00 },
    Row { r: 0x2000, g: 0x2000, b: 0x2000 },
    Row { r: 0x2100, g: 0x2100, b: 0x2100 },
    Row { r: 0x2200, g: 0x2200, b: 0x2200 },
    Row { r: 0x2300, g: 0x2300, b: 0x2300 },
    Row { r: 0x2400, g: 0x2400, b: 0x2400 },
    Row { r: 0x2500, g: 0x2500, b: 0x2500 },
    Row { r: 0x2600, g: 0x2600, b: 0x2600 },
    Row { r: 0x2700, g: 0x2700, b: 0x2700 },
    Row { r: 0x7000, g: 0x7000, b: 0x7000 },
    Row { r: 0x7100, g: 0x7100, b: 0x7100 },
    Row { r: 0x7200, g: 0x7200, b: 0x7200 },
    Row { r: 0x7300, g: 0x7300, b: 0x7300 },
    Row { r: 0x74a0, g: 0x74a0, b: 0x74a0 },
];
static ICND1065_WRAPPERS: [Row; 4] = [
    Row { r: 0x00aa, g: 0x00aa, b: 0x00aa },
    Row { r: 0x01aa, g: 0x01aa, b: 0x01aa },
    Row { r: 0x0055, g: 0x0055, b: 0x0055 },
    Row { r: 0x0155, g: 0x0155, b: 0x0155 },
];

/// Every chip this firmware can configure, by name.
pub static CHIPS: [Chip; 2] = [
    Chip {
        name: "dp3364s",
        regs: &DP3364S_REGS,
        wrappers: &DP3364S_WRAPPERS,
        slots: 1,
        rot_slot: 0,
        mid_latch: false,
        scan_reg: 0x02,
        scan_mask: 0x3f,
        bright_reg: 0x08,
        bright_max: 0x7f,
        capture_scan: 64,
    },
    Chip {
        name: "icnd1065",
        regs: &ICND1065_REGS,
        wrappers: &ICND1065_WRAPPERS,
        slots: 5,
        rot_slot: 2,
        mid_latch: true,
        scan_reg: 0x02,
        scan_mask: 0x3f,
        bright_reg: 0x00,
        bright_max: 0x7f,
        capture_scan: 43,
    },
];

/// Look a chip up by the name marquee serves in the boot config.
pub fn by_name(name: &str) -> Option<&'static Chip> {
    CHIPS.iter().find(|c| c.name == name)
}
