#!/usr/bin/env python3
"""Generate the firmware's chip tables from gateware/spwm_chips.py.

ONE source of truth. The gateware's default table and the firmware's runtime
table describe the same chip, and a copy-paste between Python and Rust is a
place for them to drift silently -- the panel would light with the wrong
configuration and look merely "a bit off" rather than broken.

This repo has been bitten by exactly that before: `half_words` existed in three
places and the display and the DMA addressed different halves of the
framebuffer. The answer then was a build-time guard; the answer here is to not
have a second copy at all.

    ./build.sh spwm-tables      # regenerate after editing spwm_chips.py
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "gateware"))

from spwm_chips import CHIPS, MAX_REGS, MAX_WRAPPERS  # noqa: E402

OUT = os.path.join(os.path.dirname(__file__), "..", "sw_rust", "barsign_disp",
                   "src", "spwm_tables.rs")


def main():
    names = sorted(CHIPS)
    lines = [
        "// GENERATED by tools/gen_spwm_tables.py from gateware/spwm_chips.py.",
        "// Do not edit: edit the Python and regenerate (`./build.sh spwm-tables`).",
        "//",
        "// These are S-PWM driver-chip register tables. The gateware is one engine",
        "// and the chip is data; this is that data, in the form the firmware writes",
        "// over the chip_table CSR at boot.",
        "//",
        "// NOTHING HERE HAS BEEN TESTED ON HARDWARE.",
        "",
        "/// One register row: the same address on three separate driver chips,",
        "/// which do not have to carry the same value.",
        "#[derive(Clone, Copy)]",
        "pub struct Row {",
        "    pub r: u16,",
        "    pub g: u16,",
        "    pub b: u16,",
        "}",
        "",
        "/// A chip's protocol data: the rotating registers, the wrapper slots,",
        "/// and the three grammar bits that differ between parts.",
        "pub struct Chip {",
        "    pub name: &'static str,",
        "    pub regs: &'static [Row],",
        "    pub wrappers: &'static [Row],",
        "    pub slots: u8,",
        "    pub rot_slot: u8,",
        "    pub mid_latch: bool,",
        "    /// Register address carrying the scan row count, and its mask.",
        "    pub scan_reg: u8,",
        "    pub scan_mask: u8,",
        "    /// Register address carrying output current, if this chip has one.",
        "    pub bright_reg: u8,",
        "    pub bright_max: u8,",
        "    /// Scan rate the capture was taken at. A table used at a different",
        "    /// scan rate is an extrapolation -- registers other than the scan",
        "    /// count do change with it.",
        "    pub capture_scan: u16,",
        "}",
        "",
        f"pub const MAX_REGS: usize = {MAX_REGS};",
        f"pub const MAX_WRAPPERS: usize = {MAX_WRAPPERS};",
        "",
    ]

    for name in names:
        c = CHIPS[name]
        u = name.upper()
        lines.append(f"// {c.name}: {c.source}")
        if c.note:
            lines.append(f"// {c.note}")
        lines.append(f"static {u}_REGS: [Row; {len(c.regs)}] = [")
        for r, g, b in c.regs:
            lines.append(f"    Row {{ r: 0x{r:04x}, g: 0x{g:04x}, b: 0x{b:04x} }},")
        lines.append("];")
        if c.wrappers:
            lines.append(f"static {u}_WRAPPERS: [Row; {len(c.wrappers)}] = [")
            for r, g, b in c.wrappers:
                lines.append(f"    Row {{ r: 0x{r:04x}, g: 0x{g:04x}, b: 0x{b:04x} }},")
            lines.append("];")
        else:
            lines.append(f"static {u}_WRAPPERS: [Row; 0] = [];")
        lines.append("")

    lines.append("/// Every chip this firmware can configure, by name.")
    lines.append(f"pub static CHIPS: [Chip; {len(names)}] = [")
    for name in names:
        c = CHIPS[name]
        u = name.upper()
        lines += [
            "    Chip {",
            f'        name: "{c.name}",',
            f"        regs: &{u}_REGS,",
            f"        wrappers: &{u}_WRAPPERS,",
            f"        slots: {c.slots},",
            f"        rot_slot: {c.rot_slot},",
            f"        mid_latch: {str(c.mid_latch).lower()},",
            f"        scan_reg: 0x{c.scan_reg:02x},",
            f"        scan_mask: 0x{c.scan_mask:02x},",
            f"        bright_reg: 0x{(c.bright_reg or 0):02x},",
            f"        bright_max: 0x{c.bright_max:02x},",
            f"        capture_scan: {c.capture_scan or 0},",
            "    },",
        ]
    lines.append("];")
    lines.append("")
    lines.append("/// Look a chip up by the name marquee serves in the boot config.")
    lines.append("pub fn by_name(name: &str) -> Option<&'static Chip> {")
    lines.append("    CHIPS.iter().find(|c| c.name == name)")
    lines.append("}")
    lines.append("")

    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))
    print(f"wrote {OUT}: {len(names)} chips, "
          f"{sum(len(CHIPS[n].regs) for n in names)} register rows")


if __name__ == "__main__":
    main()
