#!/usr/bin/env python3
"""Rasterise fonts and SVG icons into 4bpp sprites, emitted as Rust.

The build-time half of the asset pipeline in docs/DISPLAY-PROGRAMS.md §7. An
outline glyph and an SVG icon are the SAME output -- a rectangle of 4-bit
coverage -- so they go through one rasteriser and one consumer on the panel.

Why coverage rather than colour: the panel blits `ramp_base + nibble`, one add,
with no blend. Colour lives in 16 palette entries, so recolouring an asset never
touches the framebuffer.

Why build-time: runtime SVG on a 40 MHz core needs a parser plus an
anti-aliasing path rasteriser, allocating -- and buys nothing, because the
target size is always known here.

    python3 tools/mkassets.py > sw_rust/barsign_disp/src/assets.rs
"""
import io, sys, unicodedata
from PIL import Image, ImageFont
import cairosvg

FONT_PATH = "assets/fonts/DejaVuSans.ttf"

# Weight 400-500 at these sizes; HUB75.md: above ~10px heavier is WORSE, a
# weight-600 stroke closes both counters of an 8 at 20px.
FONTS = [("big", 30), ("small", 13)]
GLYPHS = "0123456789.,:-+ °%ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

ICONS = [("sun", "assets/icons/sun.svg", 22), ("drop", "assets/icons/drop.svg", 22)]


def pack4(img):
    """L-mode image -> 4bpp, two pixels per byte, high nibble first."""
    w, h = img.size
    px = img.load()
    out = bytearray((w * h + 1) // 2)
    for i in range(w * h):
        v = px[i % w, i // w] >> 4          # 8bpp coverage -> 4bpp
        if i & 1 == 0:
            out[i >> 1] |= v << 4
        else:
            out[i >> 1] |= v
    return bytes(out), w, h


def rust_bytes(b):
    return ",".join(str(x) for x in b)


def emit_sprite(name, data, w, h):
    print(f"pub static {name}_DATA: [u8; {len(data)}] = [{rust_bytes(data)}];")


def main():
    print("// GENERATED by tools/mkassets.py -- do not edit.")
    print("//")
    print("// 4bpp coverage sprites: fonts and SVG icons, one format, one consumer.")
    print("// Regenerate with:  python3 tools/mkassets.py > src/assets.rs")
    print("#![allow(dead_code)]")
    print("use crate::sprite::{Font, Glyph, Sprite};\n")

    for fname, size in FONTS:
        f = ImageFont.truetype(FONT_PATH, size)
        ascent, descent = f.getmetrics()
        entries = []
        for ch in GLYPHS:
            mask = f.getmask(ch, mode="L")
            gw, gh = mask.size
            bbox = f.getbbox(ch)
            adv = int(round(f.getlength(ch)))
            if gw == 0 or gh == 0:
                entries.append((ch, b"", 0, 0, 0, 0, adv))
                continue
            img = Image.frombytes("L", (gw, gh), bytes(mask))
            data, w, h = pack4(img)
            sym = f"F_{fname.upper()}_{ord(ch):04X}"
            emit_sprite(sym, data, w, h)
            # bbox[1] is the top of the ink relative to the text origin's ascent
            entries.append((ch, data, w, h, bbox[0], bbox[1] - ascent, adv))

        print(f"\npub static FONT_{fname.upper()}_GLYPHS: [Glyph; {len(entries)}] = [")
        for ch, data, w, h, xo, yo, adv in entries:
            sym = f"F_{fname.upper()}_{ord(ch):04X}"
            arr = f"&{sym}_DATA" if data else "&[]"
            esc = {"'": "\\'", "\\": "\\\\"}.get(ch, ch)
            print(f"    Glyph {{ ch: '{esc}', sprite: Sprite {{ w: {w}, h: {h}, data: {arr} }}, "
                  f"xoff: {xo}, yoff: {yo}, advance: {adv} }},")
        print("];")
        print(f"pub static FONT_{fname.upper()}: Font = Font {{ glyphs: &FONT_{fname.upper()}_GLYPHS, "
              f"ascent: {ascent}, line_height: {ascent + descent} }};\n")

    for iid, path, size in ICONS:
        png = cairosvg.svg2png(url=path, output_width=size, output_height=size)
        img = Image.open(io.BytesIO(png)).convert("RGBA")
        alpha = img.split()[3]                      # coverage IS the alpha channel
        data, w, h = pack4(alpha)
        sym = f"ICON_{iid.upper()}"
        emit_sprite(sym, data, w, h)
        print(f"pub static {sym}: Sprite = Sprite {{ w: {w}, h: {h}, data: &{sym}_DATA }};\n")


if __name__ == "__main__":
    main()
