#!/usr/bin/env python3
"""panelc -- compile a panel YAML into Rust that runs ON the panel.

The ESPHome bargain: YAML is a BUILD-TIME artifact. It generates code, the code
is compiled into the firmware, and what runs on the device is native. Nothing
here is parsed on the panel -- DISPLAY-PROGRAMS §5 measured a per-pixel
interpreter at ~0.3 fps, which is why this is a compiler and not a VM.

Emits two files:
    src/assets.rs     4bpp coverage sprites: fonts and SVG icons, one pipeline
    src/generated.rs  one render fn per program, plus a name->fn registry

A program is a pure fn of (ctx, x, y) -> palette index. Widgets compile to
ordered early-returns; the first that covers a pixel wins. A `lambda:` widget
splices raw Rust in at its position in that order, so user code composes with
declarative widgets instead of living beside them.

    python3 tools/panelc.py panels/*.yaml
"""
import io, os, re, sys, glob
import yaml
from PIL import Image, ImageFont
import cairosvg

OUT_ASSETS = "sw_rust/barsign_disp/src/assets.rs"
OUT_PROGS = "sw_rust/barsign_disp/src/generated.rs"

# Ramps are 16 consecutive palette entries; flat colours sit below them. Keep in
# step with program::palette() -- they are two halves of one layout.
COLORS = {
    "bg": ("flat", "BG"), "slate": ("ramp", "RAMP_SLATE"),
    "brass": ("ramp", "RAMP_BRASS"), "white": ("ramp", "RAMP_WHITE"),
    "water": ("ramp", "RAMP_WATER"), "alert": ("flat", "ALERT"),
}
FLAT = {"slate": "SLATE", "brass": "BRASS", "alert": "ALERT", "bg": "BG"}

GLYPHS = ("0123456789.,:-+/ °%'\"!?()"
          "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz")


def pack4(img):
    w, h = img.size
    px = img.load()
    out = bytearray((w * h + 1) // 2)
    for i in range(w * h):
        v = px[i % w, i // w] >> 4
        out[i >> 1] |= (v << 4) if i & 1 == 0 else v
    return bytes(out), w, h


def emit_assets(specs, out):
    w = out.write
    w("// GENERATED by tools/panelc.py -- do not edit.\n")
    w("//\n// 4bpp coverage sprites. An SVG icon and a large glyph are the same\n")
    w("// asset type, so they share one rasteriser and one consumer (sprite.rs).\n")
    w("#![allow(dead_code)]\nuse crate::sprite::{Font, Glyph, Sprite};\n\n")

    for f in specs["fonts"]:
        name, path, size = f["name"], f["file"], f["size"]
        font = ImageFont.truetype(path, size)
        ascent, descent = font.getmetrics()
        rows = []
        for ch in GLYPHS:
            mask = font.getmask(ch, mode="L")
            adv = int(round(font.getlength(ch)))
            gw, gh = mask.size
            if not gw or not gh:
                rows.append((ch, None, 0, 0, 0, 0, adv)); continue
            data, ww, hh = pack4(Image.frombytes("L", (gw, gh), bytes(mask)))
            bb = font.getbbox(ch)
            sym = f"F_{name.upper()}_{ord(ch):04X}"
            w(f"static {sym}: [u8; {len(data)}] = [{','.join(map(str, data))}];\n")
            rows.append((ch, sym, ww, hh, bb[0], bb[1] - ascent, adv))
        w(f"\npub static FONT_{name.upper()}_G: [Glyph; {len(rows)}] = [\n")
        for ch, sym, ww, hh, xo, yo, adv in rows:
            arr = f"&{sym}" if sym else "&[]"
            esc = ch.replace("\\", "\\\\").replace("'", "\\'")
            w(f"    Glyph {{ ch: '{esc}', sprite: Sprite {{ w: {ww}, h: {hh}, data: {arr} }},"
              f" xoff: {xo}, yoff: {yo}, advance: {adv} }},\n")
        w("];\n")
        # ASCII -> glyph index, so lookup is an array read instead of a scan.
        idx = {}
        for i, (ch, *_rest) in enumerate(rows):
            if 32 <= ord(ch) < 128:
                idx[ord(ch)] = i
        table = ",".join(str(idx.get(c, 255)) for c in range(32, 128))
        w(f"pub static FONT_{name.upper()}_A: [u8; 96] = [{table}];\n")
        # A fixed advance is what makes scrolling text O(1) per pixel.
        advs = {r[6] for r in rows if r[1] is not None}
        fixed = advs.pop() if len(advs) == 1 else 0
        # Stated, not inferred: the consumer cannot see that a runtime field is
        # a power of two, and a divide it could have shifted is a software
        # routine on this core.
        shift = fixed.bit_length() - 1 if fixed and (fixed & (fixed - 1)) == 0 else 0
        w(f"pub static FONT_{name.upper()}: Font = Font {{ glyphs: &FONT_{name.upper()}_G,"
          f" ascent: {ascent}, line_height: {ascent + descent},"
          f" fixed_advance: {fixed}, adv_shift: {shift},"
          f" ascii: &FONT_{name.upper()}_A }};\n")
        # The same number as a const. A band test is the hottest comparison in a
        # program -- once per widget per row -- and reading it from the Font
        # struct is a load from SDRAM that the display DMA is already saturating.
        # panelc knows the value at compile time, so the test should be a
        # compare against an immediate.
        w(f"pub const FONT_{name.upper()}_LH: usize = {ascent + descent};\n\n")

    if specs["fonts"]:
        first = specs["fonts"][0]["name"].upper()
        w("/// A stable handle for /api/profile, which measures glyph cost but has no\n")
        w("/// way to know what any particular program calls its faces.\n")
        w(f"pub static PROFILE_FONT: &Font = &FONT_{first};\n\n")

    for ic in specs["icons"]:
        name, path, size = ic["name"], ic["file"], ic["size"]
        png = cairosvg.svg2png(url=path, output_width=size, output_height=size)
        alpha = Image.open(io.BytesIO(png)).convert("RGBA").split()[3]
        data, ww, hh = pack4(alpha)
        sym = f"ICON_{name.upper()}"
        w(f"static {sym}_D: [u8; {len(data)}] = [{','.join(map(str, data))}];\n")
        w(f"pub static {sym}: Sprite = Sprite {{ w: {ww}, h: {hh}, data: &{sym}_D }};\n\n")


def cond_expr(s, keys=None):
    """`cond == 'rainy'` -> a Rust comparison against a hoisted value.

    `keys` is the ordered set of value keys this program reads. When it is
    given, the comparison is emitted against the per-ROW local `v_<key>`
    instead of calling `ctx.val()` -- which is a linear scan of the value
    table with a string compare per slot, and was being run once per widget
    for every one of 16384 pixels. Measured on dashboard-home: 20268 cycles
    per pixel against a 10-cycle bare store.
    """
    if not s:
        return None
    for op in ("==", "!="):
        if op in s:
            k, v = [p.strip() for p in s.split(op, 1)]
            lit = f'"{v.strip(chr(39))}"'
            if keys is None:
                return f'ctx.val("{k}") {op} {lit}'
            keys[k] = True
            return f'v_{ident(k)} {op} {lit}'
    raise SystemExit(f"panelc: cannot parse when: {s!r}")


def ident(name: str) -> str:
    """A valid Rust identifier for a program name.

    The program name is BOTH a user-facing string (what you select in marquee,
    what `by_name` matches) and the stem of half a dozen generated symbols --
    `px_`, `render_`, `palette_`, `DYNAMIC_`, `SCROLL_`. Those are two
    different alphabets, and they were the same string until a program called
    `dashboard-home` emitted `fn px_dashboard-home(...)` and the firmware would
    not compile. A hyphen is an obvious thing to put in a name.

    So: symbols are sanitised, the NAME is left alone. Anything that is not
    alphanumeric or underscore becomes an underscore, and a leading digit gets
    a prefix, because an identifier may not start with one.
    """
    out = re.sub(r"[^0-9A-Za-z_]", "_", name)
    if not out or out[0].isdigit():
        out = "p_" + out
    return out


def emit_program(doc, w):
    name = doc["program"]
    # NOT `sym`: that name is reused below for icon symbols, and an icon
    # widget would clobber it before the row driver is emitted.
    fnid = ident(name)
    disp = doc.get("display", {})
    fmap, imap = doc.get("_fonts", {}), doc.get("_icons", {})
    def fsym_of(n):
        u = n.upper()
        if u not in fmap:
            raise SystemExit(f"panelc: {name}: font {n!r} is not in this program's assets")
        return fmap[u]
    def isym_of(n):
        u = n.upper()
        if u not in imap:
            raise SystemExit(f"panelc: {name}: icon {n!r} is not in this program's assets")
        return imap[u]

    widgets = [next(iter(wd.items())) for wd in doc.get("widgets", [])]
    keys = {}          # value keys this program reads, in first-use order
    pro, px = [], []   # per-row prologue lines, per-pixel body lines
    gates = []         # the per-widget "can this row ink" flags

    for k, (kind, spec) in enumerate(widgets):
        if kind == "border":
            c = FLAT[spec.get("color", "slate")]
            px.append(f"            if x == 0 || y == 0 || x == ctx.w - 1 || y == ctx.h - 1 "
                      f"{{ return {c} as u32; }}\n")
        elif kind in ("text", "value"):
            at, font = spec["at"], spec["font"].upper()
            fsym_of(spec["font"])   # fail loudly if the program never declared it
            ramp = COLORS[spec.get("color", "white")][1]
            guard = cond_expr(spec.get("when"), keys)
            src = f'"{spec["value"]}"' if kind == "text" else f'ctx.val("{spec["key"]}")'
            # `prefix`/`suffix` compose a label around a value the way the
            # streamed scene language does with "HUMIDITY {bus:...}%". Without
            # it the same line needs three widgets at hand-computed x offsets,
            # which cannot be centred as a unit -- and centring is most of what
            # makes the streamed version read as designed rather than as a
            # terminal. Built ONCE per row, into a buffer owned by the row.
            pre, suf = spec.get("prefix", ""), spec.get("suffix", "")
            if pre or suf:
                pro.append(f"    let mut b_{k} = [0u8; 48];\n")
                src = f'join3(&mut b_{k}, "{pre}", {src}, "{suf}")'
            band = f"y >= {at[1]} && y < {at[1]} + FONT_{font}_LH"
            ox = (f"if ctx.w > tw {{ (ctx.w - tw) / 2 }} else {{ 2 }}"
                  if at[0] == "center" else f"{at[0]}")
            gates.append(f"g_{k}")
            pro.append(f"    // {kind} {spec.get('key', spec.get('value', ''))!r}\n")
            pro.append(f"    let g_{k} = {band}" + (f" && ({guard})" if guard else "") + ";\n")
            # width() walks the run; it buys BOTH the centring and the
            # horizontal reject, and it happens once per row instead of 128
            # times. +4 for glyph overhang past the last advance.
            pro.append(f"    let (s_{k}, o_{k}, e_{k}) = if g_{k} {{\n")
            pro.append(f"        let s = {src};\n")
            pro.append(f"        let tw = FONT_{font}.width(s);\n")
            pro.append(f"        let ox = {ox};\n")
            pro.append(f"        (s, ox, ox + tw + 4)\n")
            pro.append(f"    }} else {{ (\"\", 0usize, 0usize) }};\n")
            # Reject on the x extent BEFORE cover_at, which walks the glyph run
            # from the start of the string for every pixel -- 410 cycles for an
            # 8-character label, measured, against 11 for a store.
            px.append(f"            if g_{k} && x >= o_{k} && x < e_{k} {{\n")
            px.append(f"                if let Some(c) = FONT_{font}.cover_at(s_{k}, x, y, o_{k}, {at[1]}) "
                      f"{{ return ({ramp} + c) as u32; }}\n")
            px.append("            }\n")
        elif kind == "icon":
            at = spec["at"]
            ramp = COLORS[spec.get("color", "white")][1]
            guard = cond_expr(spec.get("when"), keys)
            isym_of(spec["name"])   # fail loudly if the program never declared it
            isym = f"ICON_{spec['name'].upper()}"
            gates.append(f"g_{k}")
            pro.append(f"    // icon {spec['name']!r}\n")
            pro.append(f"    let g_{k} = y >= {at[1]} && y < {at[1]} + {isym}.h as usize"
                       + (f" && ({guard})" if guard else "") + ";\n")
            px.append(f"            if g_{k} && x >= {at[0]} && x < {at[0]} + {isym}.w as usize {{\n")
            px.append(f"                if let Some(c) = {isym}.cover_at(x, y, {at[0]}, {at[1]}) "
                      f"{{ return ({ramp} + c) as u32; }}\n")
            px.append("            }\n")
        elif kind == "lambda":
            # Two forms. A bare string is per-pixel code, as it always was. A
            # mapping may also carry `row:`, which is spliced into the per-row
            # prologue -- the same hoisting the declarative widgets get, for the
            # one widget kind panelc cannot analyse. Without it a lambda pays
            # ctx.val() (79 cycles) per PIXEL for a test that is constant across
            # the row, which is what made the power trace the most expensive
            # thing on the panel after the declarative widgets were fixed.
            if isinstance(spec, dict):
                rowsrc, pxsrc = spec.get("row", ""), spec["px"]
            else:
                rowsrc, pxsrc = "", spec
            if rowsrc:
                pro.append("    // ---- lambda row: prologue (verbatim) ----\n")
                for line in rowsrc.rstrip().splitlines():
                    pro.append(f"    {line}\n")
            px.append("            // ---- lambda (verbatim from the YAML) ----\n")
            px.append("            if let Some(i) = (|| -> Option<u8> {\n")
            for line in pxsrc.rstrip().splitlines():
                px.append(f"                {line}\n")
            px.append("            })() { return i as u32; }\n")
        else:
            raise SystemExit(f"panelc: unknown widget {kind!r}")

    # A lambda or a border may ink ANY row, so a row where no widget's band
    # matches can only be skipped when the program has neither.
    catchall = any(k in ("lambda", "border") for k, _ in widgets)

    w(f"/// Generated from panels/{name}.yaml -- edit the YAML, not this.\n")
    w("///\n")
    w("/// ONE function per row, in two halves: a prologue of everything that\n")
    w("/// depends on y but not x, then the pixel loop. That split is the whole\n")
    w("/// reason a program is affordable, and it is why the prologue is inlined\n")
    w("/// here rather than living in a helper -- a `lambda` widget's own `row:`\n")
    w("/// block is spliced into it, and its locals have to be visible to the\n")
    w("/// loop body below.\n")
    w("///\n")
    w("/// The band test, the `when:` guard, the value lookup and the centring\n")
    w("/// width() all depend only on the row, but were once evaluated inside the\n")
    w("/// pixel loop, per widget, for all 16384 pixels. `ctx.val()` is a linear\n")
    w("/// scan of the value table, and a four-page program asks `page == 'N'` in\n")
    w("/// every widget, so a pixel paid for ~24 of them. Measured on\n")
    w("/// dashboard-home: 20268 cycles per pixel, against 11 for a bare store.\n")
    w(f"pub fn render_{fnid}(ctx: &Ctx, y: usize, x0: usize, row: &mut [u32]) {{\n")
    w(f"    let _ = (&ctx, y, x0);\n")
    # THIS is what makes `big` mean this program's `big`. Assets are stored
    # under a symbol derived from file+size so two programs cannot collide, and
    # each program rebinds its own names here -- so a hand-written lambda can
    # still say FONT_TICK, and say it about the right face.
    for alias, sym in sorted(fmap.items()):
        w(f"    #[allow(non_snake_case)] let FONT_{alias} = &FONT_{sym};\n")
        w(f"    #[allow(non_upper_case_globals)] const FONT_{alias}_LH: usize = FONT_{sym}_LH;\n")
    for alias, sym in sorted(imap.items()):
        w(f"    #[allow(non_snake_case)] let ICON_{alias} = &ICON_{sym};\n")
    for kk in keys:
        w(f"    let v_{ident(kk)} = ctx.val(\"{kk}\");\n")
    for line in pro:
        w(line)
    if gates and not catchall:
        # No lambda and no border: a row no widget's band reaches is background,
        # and filling it is one store per pixel instead of a walk of every widget.
        w(f"    if !({' || '.join(gates)}) {{\n")
        w(f"        for p in row.iter_mut() {{ *p = BG as u32; }}\n")
        w(f"        return;\n")
        w("    }\n")
    # iter_mut, not row[x]: indexing bounds-checks every store, and the store
    # path is the bottleneck here -- measured, the indirect call was not.
    w(f"    for (i, p) in row.iter_mut().enumerate() {{\n")
    w(f"        let x = x0 + i;\n")
    w(f"        *p = (|| -> u32 {{\n")
    for line in px:
        w(line)
    w("            BG as u32\n")
    w("        })();\n")
    w("    }\n}\n\n")
    # Dynamic band: the rows that change every frame. Everything outside it is
    # redrawn only when it can actually have changed (a value arrived, or the
    # other buffer has not seen this content yet). A framebuffer store costs
    # ~190 cycles on this core, so not writing a word is the only real speedup.
    scr = doc.get("scroll") or []
    if isinstance(scr, dict):
        scr = [scr]
    w(f"/// Scroll bands from `scroll:` in the YAML: (y0, y1, speed, rightward).\n")
    w(f"pub const SCROLL_{fnid.upper()}: &[(usize, usize, usize, bool)] = &[\n")
    for b in scr:
        right = "true" if str(b.get("dir", "left")).lower() == "right" else "false"
        w(f"    ({b['band'][0]}, {b['band'][1]}, {b.get('speed', 1)}, {right}),\n")
    w("];\n\n")

    dyn = disp.get("dynamic")
    if dyn:
        w(f"/// Rows that change every frame, from `display.dynamic` in the YAML.\n")
        w(f"pub const DYNAMIC_{fnid.upper()}: Option<(usize, usize)> = Some(({dyn[0]}, {dyn[1]}));\n\n")
    else:
        w(f"/// No `display.dynamic` declared: every row is treated as changing.\n")
        w(f"pub const DYNAMIC_{fnid.upper()}: Option<(usize, usize)> = None;\n\n")

    pal = doc.get("palette")
    pal_static = bool(pal) and "ctx" not in pal
    if pal:
        w(f"/// Per-frame palette from `palette:` in the YAML. 256 words a frame --\n")
        w(f"/// the cheapest animation available, and flat in wall size.\n")
        w(f"pub fn palette_{fnid}(ctx: &Ctx, i: usize) -> u32 {{\n")
        w(f"    let _ = (&ctx, i);\n")
        for line in pal.rstrip().splitlines():
            w(f"    {line}\n")
        w("}\n\n")

    return (name, bool(pal), pal_static)


def main(paths):
    docs = [yaml.safe_load(open(p)) for p in paths]
    # Assets are keyed by WHAT THEY ARE (file + size), never by the alias a
    # program happens to give them. Keying on the name meant the first program
    # to say `big` defined it for every program: hello.yaml's `big` is
    # DejaVuSans-Bold at 20, so dashboard-home's `big` (DejaVuSans 30) was
    # silently discarded and every hero number on that panel rendered two
    # thirds the intended size in the wrong weight. Nothing warned, because
    # from the generator's point of view the name was simply already defined.
    #
    # Each program keeps its own alias -> symbol map, so two programs may use
    # the same word for different faces, and identical faces are still shared.
    fonts, icons, fsym, isym = [], [], {}, {}
    for d in docs:
        a = d.get("assets", {})
        d["_fonts"], d["_icons"] = {}, {}
        for f in a.get("fonts", []):
            key = (f["file"], f["size"])
            if key not in fsym:
                stem = re.sub(r"[^0-9A-Za-z]", "", os.path.splitext(os.path.basename(f["file"]))[0])
                fsym[key] = f"{stem}_{f['size']}".upper()
                fonts.append(dict(f, name=fsym[key]))
            d["_fonts"][f["name"].upper()] = fsym[key]
        for i in a.get("icons", []):
            key = (i["file"], i["size"])
            if key not in isym:
                stem = re.sub(r"[^0-9A-Za-z]", "", os.path.splitext(os.path.basename(i["file"]))[0])
                isym[key] = f"{stem}_{i['size']}".upper()
                icons.append(dict(i, name=isym[key]))
            d["_icons"][i["name"].upper()] = isym[key]
    with open(OUT_ASSETS, "w") as out:
        emit_assets({"fonts": fonts, "icons": icons}, out)

    with open(OUT_PROGS, "w") as out:
        out.write("// GENERATED by tools/panelc.py -- do not edit.\n//\n")
        out.write("// Compiled from panels/*.yaml. Widgets become ordered early-returns;\n")
        out.write("// a lambda is spliced in verbatim at its position in that order.\n")
        out.write("#![allow(unused_imports, unused_parens, unused_variables, clippy::all)]\n")
        out.write("use crate::assets::*;\nuse crate::prim::*;\nuse crate::program::*;\n\n")
        names = [emit_program(d, out.write) for d in docs]
        out.write("/// Programs by name, so `mode: program` can select one at runtime\n")
        out.write("/// without a per-panel firmware -- marquee cannot do that (TODO item 8).\n")
        out.write("/// Every program in this firmware. One firmware carries them all and\n")
        out.write("/// the config picks which runs -- marquee cannot do per-panel firmware.\n")
        out.write(f"pub static PROGRAMS: [Program; {len(names)}] = [\n")
        for n, has_pal, pal_static in names:
            # `name:` keeps the name as written -- that is what marquee sends
            # and what by_name matches. Everything else is the sanitised symbol.
            i = ident(n)
            pal = f"Some(palette_{i})" if has_pal else "None"
            out.write(f'    Program {{ name: "{n}", row: render_{i}, '
                      f'palette_static: {"true" if pal_static else "false"}, '
                      f'dynamic: DYNAMIC_{i.upper()}, scroll: SCROLL_{i.upper()}, '
                      f'palette: {pal} }},\n')
        out.write("];\n\n")
        out.write("pub fn by_name(n: &str) -> Option<&'static Program> {\n")
        out.write("    PROGRAMS.iter().find(|p| p.name == n)\n}\n")
    print(f"panelc: {len(docs)} program(s), {len(fonts)} font(s), {len(icons)} icon(s)", file=sys.stderr)


if __name__ == "__main__":
    main(sys.argv[1:] or glob.glob("panels/*.yaml"))
